// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoiDkMyV4aCSWVaMdJCcjqJOxmpxHdzXk',
    appId: '1:75816049578:web:9761c32e26ba84ddf929d3',
    messagingSenderId: '75816049578',
    projectId: 'one-one-3ea4a',
    authDomain: 'one-one-3ea4a.firebaseapp.com',
    storageBucket: 'one-one-3ea4a.appspot.com',
    measurementId: 'G-RVK074BJ6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYqUY2QLbbtBliRY9e8sH-_lLwMvB5F8',
    appId: '1:75816049578:android:0cb4fa0f2829bce0f929d3',
    messagingSenderId: '75816049578',
    projectId: 'one-one-3ea4a',
    storageBucket: 'one-one-3ea4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bZqracBT42-uni1nHN_P9iLrzx-Iv_E',
    appId: '1:75816049578:ios:6e0bd28f04fe646bf929d3',
    messagingSenderId: '75816049578',
    projectId: 'one-one-3ea4a',
    storageBucket: 'one-one-3ea4a.appspot.com',
    iosClientId: '75816049578-a126irhq6tqje1cp3a8t589rvmjuplh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGolangYt',
  );
}
